right_format = "${custom.arch}${time}"

[aws]
symbol = " "

[battery]
disabled = true

[custom.arch]
disabled = true
command = "uname -m"
shell = "sh"
when = true

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[git_branch]
# disabled = true
symbol = "󰘬 "

# [git_commit]
# disabled = true

# [git_state]
# disabled = true

# [git_status]
# disabled = true

[kubernetes]
contexts = [
    { context_pattern = "^arn:aws:eks:.*/(?P<cluster>.*)$", context_alias = "$cluster" },
]
disabled = false
detect_env_vars = ['KUBECONFIG']

[time]
disabled = false
