right_format = "${custom.arch}${time}"

[battery]
disabled = true

[custom.arch]
command = "uname -m"
shell = "sh"
when = true

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[git_branch]
symbol = "ó°˜¬ "

[kubernetes]
contexts = [
    { context_pattern = "^arn:aws:eks:.*/(?P<cluster>.*)$", context_alias = "$cluster" },
]
disabled = false
detect_env_vars = ['KUBECONFIG']

[time]
disabled = false
